### ISSUE TITLE
Errors in Schema check.

### ISSUE THREAD

**Issue by petervanvogelpoel-filmbooking** [wolfgangw/digital_cinema_tools#35]
I'm getting the folowing on almost all DCPs:

Error: AM d363c7a9-6fb9-4863-8a82-4b21a35535a0: Schema check ❌: PROTO-ASDCP-AM-20040311.xsd /dcpstorage001/2015c2f0-c187-4609-d6b9-08dcd6f8de7d/Filmbooking_com_TestDCP5_1_dcp/./ASSETMAP line 7: 7:0: ERROR: Element '{http://www.digicine.com/PROTO-ASDCP-AM-20040311#}AnnotationText': This element is not expected. Expected is ( {http://www.digicine.com/PROTO-ASDCP-AM-20040311#}Creator ).

Any advice?
Peter

**Comment by wolfgangw** [comment]
Please see https://github.com/wolfgangw/digital_cinema_tools_distribution/issues/53
